name: TYGR
channels:
  - pytorch
  - defaults
dependencies:
  # Core dependencies
  - python=3.8.10
  - pytorch=1.8.1
  - cpuonly
  - pip

  # Standard Data Science libs
  - numpy=1.20.2
  - pandas==1.2.4
  - scikit-learn==0.24.2
  - networkx==2.5.1
  - sympy
  - matplotlib==3.4.2
  - tqdm

  # Pip dependencies
  - pip:
    # Binary analysis
    - angr==9.0.7491
    - pyvex==9.0.7491
    - claripy==9.0.7491
    - cle==9.0.7491
    - archinfo==9.0.7491
    - ailment==9.0.7491
    - pyelftools==0.27
    - capstone==4.0.2
    - unicorn==1.0.2rc4

   # Utilities 
    - protobuf==3.17.1
    - z3-solver==4.8.10.0
    - progressbar2==3.53.1
    - pefile==2021.5.24

  # Graph Neural Nets
    - torch-geometric==1.7.0
    # torch-sparse and torch-scatter installed in Dockerfile
